DROP TABLE IF EXISTS produtos;

CREATE TABLE IF NOT EXISTS produtos (
	id INT NOT NULL PRIMARY KEY,
	nome VARCHAR(200) NOT NULL,
	preco DECIMAL(20, 2) NOT NULL,
	score INT NOT NULL,
	image VARCHAR(200)
);